In [190]:
# PASO 1: Importamos las librerías necesarias

# Librerías con Pandas:
import pandas as pd # # Para manipular datos en tablas (DataFrames) *
import numpy as np # # Para realizar operaciones numéricas

# Configuraciones:
pd.set_option("display.max_columns", None) # Para mostrar todas las columnas del DataFrame *

# PARTE 1: EDA de los DataFrame separados
- Objetivo: Iniciar un análisis "superficial" de cada DataFrame para tener una visión clara de los datos

In [191]:
# PASO 1: Cargamos el dataset 1 (archivo .csv) y lo convertimos en un DataFrame de pandas (tabla)

df_flight = pd.read_csv("documentos iniciales/customer flight activity.csv")

df_flight.head() # Mostramos las primeras 5 filas del DataFrame para verificar que se ha cargado correctamente y tenemos una primera observación

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100018,2017,1,3,0,3,1521.0,152.0,0.0,0.0
1,100102,2017,1,10,4,14,2030.0,203.0,0.0,0.0
2,100140,2017,1,6,0,6,1200.0,120.0,0.0,0.0
3,100214,2017,1,0,0,0,0.0,0.0,0.0,0.0
4,100272,2017,1,0,0,0,0.0,0.0,0.0,0.0

In [192]:
# Cargamos el dataset 2

df_loyalty = pd.read_csv("documentos iniciales/customer loyalty history.csv")

df_loyalty.head()

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN

In [193]:
# PASO 2: Exploramos el dataset para entender su estructura y contenido

print(f"Las dimensiones de 'df_flight' es de: {df_flight.shape} filas y columans") # Muestra las dimensiones de las filas y columnas
print(f"Las dimensiones de 'df_loyalty' es de: {df_loyalty.shape} filas y columans")

Las dimensiones de 'df_flight' es de: (324333, 10) filas y columans
Las dimensiones de 'df_loyalty' es de: (16737, 16) filas y columans

In [194]:
df_flight.info() # Muestra la información de nuestro DataFrame: número de filas y columnas + nombre de lascolumnas + valores no nulos + tipos de datos

<class 'pandas.DataFrame'>
RangeIndex: 324333 entries, 0 to 324332
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               324333 non-null  int64
 1   Year                         324333 non-null  int64
 2   Month                        324333 non-null  int64
 3   Flights Booked               324333 non-null  int64
 4   Flights with Companions      324333 non-null  int64
 5   Total Flights                324333 non-null  int64
 6   Distance                     324332 non-null  float64
 7   Points Accumulated           324332 non-null  float64
 8   Points Redeemed              324332 non-null  float64
 9   Dollar Cost Points Redeemed  324332 non-null  float64
dtypes: float64(4), int64(6)
memory usage: 24.7 MB

In [195]:
df_loyalty.info()

<class 'pandas.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  str
 2   Province            16737 non-null  str
 3   City                16737 non-null  str
 4   Postal Code         16737 non-null  str
 5   Gender              16737 non-null  str
 6   Education           16737 non-null  str
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  str
 9   Loyalty Card        16737 non-null  str
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  str
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), str(9)
memory usage: 2.0 MB

In [196]:
# PASO 3: Observamos los valores nulos

round(df_flight.isna().sum().sort_values(ascending=False)/df_flight.shape[0]*100,2) # Muestra el número de valores nulos que hay por columna en porcentaje y en orden ascendente

Distance                       0.0
Points Accumulated             0.0
Points Redeemed                0.0
Dollar Cost Points Redeemed    0.0
Loyalty Number                 0.0
Year                           0.0
Month                          0.0
Flights Booked                 0.0
Flights with Companions        0.0
Total Flights                  0.0
dtype: float64

In [197]:
round(df_loyalty.isna().sum().sort_values(ascending=False)/df_loyalty.shape[0]*100,2)

Cancellation Year     87.65
Cancellation Month    87.65
Salary                25.32
Loyalty Number         0.00
Country                0.00
Province               0.00
City                   0.00
Postal Code            0.00
Gender                 0.00
Education              0.00
Marital Status         0.00
Loyalty Card           0.00
CLV                    0.00
Enrollment Type        0.00
Enrollment Year        0.00
Enrollment Month       0.00
dtype: float64

In [198]:
# PASO 4: Revisamos filas duplicadas

df_flight.duplicated().sum() # Muestra cuántos valores hay duplicados -> Copia/s

np.int64(1578)

In [199]:
df_flight[df_flight.duplicated()] # Observamos las 4 filas repetidas

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
42,101902,2017,1,0,0,0,0.0,0.0,0.0,0.0
227,112142,2017,1,0,0,0,0.0,0.0,0.0,0.0
478,126100,2017,1,0,0,0,0.0,0.0,0.0,0.0
567,130331,2017,1,0,0,0,0.0,0.0,0.0,0.0
660,135421,2017,1,0,0,0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
323145,208241,2018,8,0,0,0,0.0,0.0,0.0,0.0
323152,208485,2018,8,0,0,0,0.0,0.0,0.0,0.0
323450,224676,2018,8,0,0,0,0.0,0.0,0.0,0.0
323656,237094,2018,8,0,0,0,0.0,0.0,0.0,0.0
324161,263267,2018,8,0,0,0,0.0,0.0,0.0,0.0

In [200]:
df_flight[df_flight.duplicated(keep=False)] # Comprobamos que existen 1578 originales y +1 copia/s por cada original (3141). El primero de cada uno es el original y a partir del segundo es/son la/s copia/s -> Nos fijamos en los índices para saber cuál es la copia

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
41,101902,2017,1,0,0,0,0.0,0.0,0.0,0.0
42,101902,2017,1,0,0,0,0.0,0.0,0.0,0.0
226,112142,2017,1,0,0,0,0.0,0.0,0.0,0.0
227,112142,2017,1,0,0,0,0.0,0.0,0.0,0.0
477,126100,2017,1,0,0,0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
323450,224676,2018,8,0,0,0,0.0,0.0,0.0,0.0
323655,237094,2018,8,0,0,0,0.0,0.0,0.0,0.0
323656,237094,2018,8,0,0,0,0.0,0.0,0.0,0.0
324160,263267,2018,8,0,0,0,0.0,0.0,0.0,0.0
324161,263267,2018,8,0,0,0,0.0,0.0,0.0,0.0

In [201]:
df_flight.drop_duplicates(inplace=True) # Eliminamos los duplicados, ya que afectaria la calidad de los datos a futuro

In [202]:
df_flight.duplicated().sum() # Comprobamos los duplicados ahora = 0

np.int64(0)

In [203]:
# PASO 5: Revisamos columnas únicas para unir ambos DataFrame 

df_flight.nunique().sort_values(ascending=False) # Indica cuántos valores distintos (únicos) hay en cada columna -> Con esto podemos identificar las columnas redundantes

Loyalty Number                 16502
Distance                        4680
Points Accumulated              1546
Points Redeemed                  582
Dollar Cost Points Redeemed       49
Total Flights                     33
Flights Booked                    22
Month                             12
Flights with Companions           12
Year                               2
dtype: int64

In [204]:
df_loyalty.nunique().sort_values(ascending=False)

Loyalty Number        16737
CLV                    7984
Salary                 5890
Postal Code              55
City                     29
Enrollment Month         12
Cancellation Month       12
Province                 11
Enrollment Year           7
Cancellation Year         6
Education                 5
Marital Status            3
Loyalty Card              3
Gender                    2
Enrollment Type           2
Country                   1
dtype: int64

In [205]:
df_combinado = pd.merge(df_flight, df_loyalty, how="inner", on="Loyalty Number") # Combinamos ambos DF asegurándonos de que se juntan de manera paralela según la llave ("Loyalty Number") para evitar tener tantos valores Nulos

---------------------

# PARTE 2: EDA del DataFrame combinado

- Objetivo: Confirmar el análisis hecho por separado + Analizar de manera más profunda

In [232]:
df_combinado.head()

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,100018,2017,1,3,0,3,1521.0,152.0,0.0,0.0,Canada,Alberta,Edmonton,T9G 1W3,Female,Bachelor,92552.0,Married,Aurora,7919.20,Standard,2016,8,Desconocido,Desconocido
1,100102,2017,1,10,4,14,2030.0,203.0,0.0,0.0,Canada,Ontario,Toronto,M1R 4K3,Male,College,73447.0,Single,Nova,2887.74,Standard,2013,3,Desconocido,Desconocido
2,100140,2017,1,6,0,6,1200.0,120.0,0.0,0.0,Canada,British Columbia,Dawson Creek,U5I 4F1,Female,College,73447.0,Divorced,Nova,2838.07,Standard,2016,7,Desconocido,Desconocido
3,100214,2017,1,0,0,0,0.0,0.0,0.0,0.0,Canada,British Columbia,Vancouver,V5R 1W3,Male,Bachelor,63253.0,Married,Star,4170.57,Standard,2015,8,Desconocido,Desconocido
4,100272,2017,1,0,0,0,0.0,0.0,0.0,0.0,Canada,Ontario,Toronto,P1L 8X8,Female,Bachelor,91163.0,Divorced,Star,6622.05,Standard,2014,1,Desconocido,Desconocido

In [207]:
df_combinado.shape

(322755, 25)

In [208]:
df_combinado.info()

<class 'pandas.DataFrame'>
RangeIndex: 322755 entries, 0 to 322754
Data columns (total 25 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               322755 non-null  int64
 1   Year                         322755 non-null  int64
 2   Month                        322755 non-null  int64
 3   Flights Booked               322755 non-null  int64
 4   Flights with Companions      322755 non-null  int64
 5   Total Flights                322755 non-null  int64
 6   Distance                     322754 non-null  float64
 7   Points Accumulated           322754 non-null  float64
 8   Points Redeemed              322754 non-null  float64
 9   Dollar Cost Points Redeemed  322754 non-null  float64
 10  Country                      322755 non-null  str
 11  Province                     322755 non-null  str
 12  City                         322755 non-null  str
 13  Postal Code                  322755 non-null  str
 14  Gender                       322755 non-null  str
 15  Education                    322755 non-null  str
 16  Salary                       240886 non-null  float64
 17  Marital Status               322755 non-null  str
 18  Loyalty Card                 322755 non-null  str
 19  CLV                          322755 non-null  float64
 20  Enrollment Type              322755 non-null  str
 21  Enrollment Year              322755 non-null  int64
 22  Enrollment Month             322755 non-null  int64
 23  Cancellation Year            39605 non-null   float64
 24  Cancellation Month           39605 non-null   float64
dtypes: float64(8), int64(8), str(9)
memory usage: 61.6 MB

In [209]:
round(df_combinado.isna().sum().sort_values(ascending=False)/df_combinado.shape[0]*100,2)

Cancellation Month             87.73
Cancellation Year              87.73
Salary                         25.37
Distance                        0.00
Points Accumulated              0.00
Points Redeemed                 0.00
Dollar Cost Points Redeemed     0.00
Education                       0.00
Enrollment Month                0.00
Enrollment Year                 0.00
Enrollment Type                 0.00
CLV                             0.00
Loyalty Card                    0.00
Marital Status                  0.00
Loyalty Number                  0.00
Gender                          0.00
Postal Code                     0.00
Year                            0.00
Province                        0.00
Country                         0.00
Total Flights                   0.00
Flights with Companions         0.00
Flights Booked                  0.00
Month                           0.00
City                            0.00
dtype: float64

In [210]:
# PASO 6: Entender las estadísticas de las columnas

df_combinado.describe().T # Muestra estadísticas descriptivas de las columnas numéricas: media + desviación típica + mínima + percentiles (mediana) + máxima

,count,mean,std,min,25%,50%,75%,max
Loyalty Number,322755.0,540352.779852,257652.626661,100018.00,316644.00,538979.00,758210.00,999986.00
Year,322755.0,2017.391099,0.487997,2017.00,2017.00,2017.00,2018.00,2018.00
Month,322755.0,5.722176,3.271684,1.00,3.00,5.00,8.00,12.00
Flights Booked,322755.0,4.010624,5.232702,0.00,0.00,0.00,8.00,21.00
Flights with Companions,322755.0,1.001958,2.062947,0.00,0.00,0.00,1.00,11.00
Total Flights,322755.0,5.012582,6.526290,0.00,0.00,0.00,10.00,32.00
Distance,322754.0,1200.561734,1452.372707,0.00,0.00,0.00,2344.00,6293.00
Points Accumulated,322754.0,123.556356,149.306695,0.00,0.00,0.00,241.00,676.50
Points Redeemed,322754.0,29.577570,122.576698,0.00,0.00,0.00,0.00,876.00
Dollar Cost Points Redeemed,322754.0,2.394210,9.915802,0.00,0.00,0.00,0.00,71.00
Salary,240886.0,79205.362553,34931.874876,-58486.00,59262.00,73447.00,88513.00,407228.00
CLV,322755.0,7997.776657,6879.274236,1898.01,3985.55,5776.34,8937.12,83325.38
Enrollment Year,322755.0,2015.253902,1.980648,2012.00,2014.00,2015.00,2017.00,2018.00
Enrollment Month,322755.0,6.663079,3.399856,1.00,4.00,7.00,10.00,12.00
Cancellation Year,39605.0,2016.494483,1.376943,2013.00,2016.00,2017.00,2018.00,2018.00
Cancellation Month,39605.0,6.951547,3.442334,1.00,4.00,7.00,10.00,12.00

-----------------

# PARTE 3: Limpieza de Datos del DataFrame combinado

- Objetivo: Arreglar Datos problemáticos + Tratar Nulos

In [211]:
# PASO 1: Solucionar los números negativos de la columna "Salary" vistos en el "min" de la función "descirbe"

df_combinado.columns

Index(['Loyalty Number', 'Year', 'Month', 'Flights Booked',
       'Flights with Companions', 'Total Flights', 'Distance',
       'Points Accumulated', 'Points Redeemed', 'Dollar Cost Points Redeemed',
       'Country', 'Province', 'City', 'Postal Code', 'Gender', 'Education',
       'Salary', 'Marital Status', 'Loyalty Card', 'CLV', 'Enrollment Type',
       'Enrollment Year', 'Enrollment Month', 'Cancellation Year',
       'Cancellation Month'],
      dtype='str')

In [212]:
df_combinado["Salary"].sample(3) # A simple vista no se ve claro que existan números negativos

69722    92785.0
8108     64458.0
57411    76159.0
Name: Salary, dtype: float64

In [213]:
salarios_negativos = df_combinado[df_combinado["Salary"] < 0] # Filtramos para comporbar mejor la existencia de los datos negativos 

print(f"Número de registros con salario negativo: {len(salarios_negativos)}")

salarios_negativos.sample(3)

Número de registros con salario negativo: 398

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
142748,542976,2017,9,0,0,0,0.0,0.00,0.0,0.0,Canada,Quebec,Montreal,H2Y 4R4,Male,High School or Below,-49830.0,Divorced,Star,24127.50,2018 Promotion,2018,3,NaN,NaN
88971,366599,2017,6,18,0,18,4752.0,475.00,0.0,0.0,Canada,Ontario,Toronto,M1R 4K3,Female,Bachelor,-9081.0,Married,Star,6915.73,2018 Promotion,2018,4,NaN,NaN
234169,729561,2018,3,4,1,5,1520.0,164.16,0.0,0.0,Canada,Quebec,Quebec City,G1B 3L5,Female,Bachelor,-19332.0,Divorced,Star,5308.29,2018 Promotion,2018,2,NaN,NaN

In [214]:
df_combinado["Salary"] = df_combinado["Salary"].abs() # Transfromamos los número snegativos en números positivos

In [215]:
salarios_negativos_final = df_combinado[df_combinado["Salary"] < 0] # Comprobamos los números negativos ahora = 0

print(f"Número de registros con salario negativo: {len(salarios_negativos_final)}")

Número de registros con salario negativo: 0

In [216]:
# PASO 2: Tratar los Nulos de las columnas "Cancellation Year", "Cancellation Month" y "Salary"

round(df_combinado.isna().sum().sort_values(ascending=False)/df_flight.shape[0]*100,2)

Cancellation Month             87.73
Cancellation Year              87.73
Salary                         25.37
Distance                        0.00
Points Accumulated              0.00
Points Redeemed                 0.00
Dollar Cost Points Redeemed     0.00
Education                       0.00
Enrollment Month                0.00
Enrollment Year                 0.00
Enrollment Type                 0.00
CLV                             0.00
Loyalty Card                    0.00
Marital Status                  0.00
Loyalty Number                  0.00
Gender                          0.00
Postal Code                     0.00
Year                            0.00
Province                        0.00
Country                         0.00
Total Flights                   0.00
Flights with Companions         0.00
Flights Booked                  0.00
Month                           0.00
City                            0.00
dtype: float64

In [217]:
# COLUMNA: "Salary" --> 25.37% NaN

print(f"El tipo de dato que tiene esta columna es: {df_combinado["Salary"].dtype}") # Para saber si es una columna numérica o categórica

df_combinado[["Salary"]].sample(5) # Observamos la columna

El tipo de dato que tiene esta columna es: float64

          Salary
77768   217158.0
123115   71910.0
211658  125167.0
98600    94551.0
133256   99063.0

In [218]:
df_combinado[["Salary"]].describe().T # Observamos los datos estadísticos

,count,mean,std,min,25%,50%,75%,max
Salary,240886.0,79323.138738,34663.596508,9081.0,59262.0,73447.0,88513.0,407228.0

In [219]:
df_combinado.describe().T # Vemos si podríamos relacionarlo lógicamente con otra columna --> No

,count,mean,std,min,25%,50%,75%,max
Loyalty Number,322755.0,540352.779852,257652.626661,100018.00,316644.00,538979.00,758210.00,999986.00
Year,322755.0,2017.391099,0.487997,2017.00,2017.00,2017.00,2018.00,2018.00
Month,322755.0,5.722176,3.271684,1.00,3.00,5.00,8.00,12.00
Flights Booked,322755.0,4.010624,5.232702,0.00,0.00,0.00,8.00,21.00
Flights with Companions,322755.0,1.001958,2.062947,0.00,0.00,0.00,1.00,11.00
Total Flights,322755.0,5.012582,6.526290,0.00,0.00,0.00,10.00,32.00
Distance,322754.0,1200.561734,1452.372707,0.00,0.00,0.00,2344.00,6293.00
Points Accumulated,322754.0,123.556356,149.306695,0.00,0.00,0.00,241.00,676.50
Points Redeemed,322754.0,29.577570,122.576698,0.00,0.00,0.00,0.00,876.00
Dollar Cost Points Redeemed,322754.0,2.394210,9.915802,0.00,0.00,0.00,0.00,71.00
Salary,240886.0,79323.138738,34663.596508,9081.00,59262.00,73447.00,88513.00,407228.00
CLV,322755.0,7997.776657,6879.274236,1898.01,3985.55,5776.34,8937.12,83325.38
Enrollment Year,322755.0,2015.253902,1.980648,2012.00,2014.00,2015.00,2017.00,2018.00
Enrollment Month,322755.0,6.663079,3.399856,1.00,4.00,7.00,10.00,12.00
Cancellation Year,39605.0,2016.494483,1.376943,2013.00,2016.00,2017.00,2018.00,2018.00
Cancellation Month,39605.0,6.951547,3.442334,1.00,4.00,7.00,10.00,12.00

In [220]:
df_combinado["Salary"] = df_combinado["Salary"].fillna(df_combinado["Salary"].median()) # Optamos por la mediana global

In [221]:
df_combinado["Salary"].isna().sum() # Comprobamos los valores Nulos ahora = 0

np.int64(0)

- Explicación: `Los valores Nulos de "Salary" se sustituyeron por la mediana global` de la misma columna, ya que: 1) No se encontró relación aparente de manera lógica con otras columnas para sustituir esos valores Nulos, y 2) Al ser numérica esta columna, la mediana es mejor opción debido a que al tener media y mediana muy similares, la mediana representa mejor el centro de los datos y reduce el efecto de valores extremos

In [222]:
# COLUMNA: "Cancellation Month" --> 87.73% NaN

print(f"El tipo de dato que tiene esta columna es: {df_combinado["Cancellation Month"].dtype}") 

df_combinado[["Cancellation Month"]].sample(5)

El tipo de dato que tiene esta columna es: float64

        Cancellation Month
26729                  NaN
91159                  NaN
35604                  NaN
58563                  NaN
137036                 2.0

In [223]:
df_combinado["Cancellation Month"] = df_combinado["Cancellation Month"].fillna("Desconocido") # Etiquetamos los valores NaN para que no haya Nulos

In [224]:
df_combinado["Cancellation Month"].isna().sum() # Comprobamos los valores Nulos ahora = 0

np.int64(0)

- Explicación: `Los valores Nulos de "Cancellation Month" se sustituyeron por la etiqueta "Desconocido"`, ya que en este caso los Nulos representan la ausencia de cancelación. Esta etiqueta permite distinguir aquellos clientes que sí han cancelado de los que no hay registro; que se les pueden considerar que no han cancelado.

In [225]:
# COLUMNA: "Cancellation Year" --> 87.73% NaN

print(f"El tipo de dato que tiene esta columna es: {df_combinado["Cancellation Year"].dtype}") 

df_combinado[["Cancellation Year"]].sample(5)

El tipo de dato que tiene esta columna es: float64

        Cancellation Year
135248                NaN
320598                NaN
15588              2016.0
254804             2017.0
4354                  NaN

In [226]:
df_combinado["Cancellation Year"] = df_combinado["Cancellation Year"].fillna("Desconocido") # Etiquetamos los valores NaN para que no haya Nulos

In [227]:
df_combinado["Cancellation Year"].isna().sum() # Comprobamos los valores Nulos ahora = 0

np.int64(0)

- Explicación: `Los valores Nulos de "Cancellation Year" se sustituyeron por la etiqueta "Desconocido"`, ya que en este caso los Nulos representan la ausencia de cancelación. Esta etiqueta permite distinguir aquellos clientes que sí han cancelado de los que no hay registro; que se les pueden considerar que no han cancelado.

In [228]:
round(df_combinado.isna().sum().sort_values(ascending=False)/df_flight.shape[0]*100,2) # Comprobamos los valores Nulos ahora = 0

Distance                       0.0
Points Accumulated             0.0
Points Redeemed                0.0
Dollar Cost Points Redeemed    0.0
Loyalty Number                 0.0
Education                      0.0
Cancellation Year              0.0
Enrollment Month               0.0
Enrollment Year                0.0
Enrollment Type                0.0
CLV                            0.0
Loyalty Card                   0.0
Marital Status                 0.0
Salary                         0.0
City                           0.0
Gender                         0.0
Postal Code                    0.0
Year                           0.0
Province                       0.0
Country                        0.0
Total Flights                  0.0
Flights with Companions        0.0
Flights Booked                 0.0
Month                          0.0
Cancellation Month             0.0
dtype: float64

-----------------

# PARTE 4: Exportación del DataFrame ya limpio

In [234]:
# ÚLTIMO PASO: Exportamos el DataFrame limpio para poder trabajar sobre él

df_combinado.to_csv("combinado_limpio.csv", index=False)